### ISSUE TITLE
Merge file 

### ISSUE THREAD

**Issue by congto** [hocchudong/ghichep-kubernetes#14]
@TrongTan124 

Xử lý merge file https://github.com/hocchudong/ghichep-kubernetes/blob/master/docs/kubernetes-5min/05.GiaoDienWebsite-Kubernetes.md vào phần sau cùng của file https://github.com/hocchudong/ghichep-kubernetes/blob/master/docs/kubernetes-5min/02.Caidat-Kubernetes.md

- Gợi ý: Thêm thành mục 6. Cài đặt dashboad.

**Comment by TrongTan124** [comment]
Em đã thực hiện điều chỉnh lại tài liệu. chuyển cài đặt và cấu hình dashboard k8s vào phần 6 trong tài liệu cài đặt k8s
