### ISSUE TITLE
Review document

### ISSUE THREAD

**Issue by linhlt247** [hocchudong/ghichep-kubernetes#3]
Em hoàn thiện xong tài liệu về k8s rồi ạ, anh review cho em với ạ.
Trong tài liệu, em nói lên các phần sau:
 - Giải thích các khái niệm, thành phần trong k8s. (file `concepts.md`).
 -  Triển khai k8s với 2 phương pháp.
    - Chạy trên local với minikube. (`minikube.md`)
    - Tạo cluster với kubeadm. (`kubeadm.md`)
- Các câu lệnh quản lý k8s. (`kubectl-command.md`)
- Giới thiệu volume và network trong k8s.(`volume and network.md`) Nội dung phần này em chỉ giới thiệu là chính, bởi vì:
   - volume: Các dạng volume mà k8s hỗ trợ nhiều trong đó có dạng chính là mount thư mục của node vào container tương tự docker. Ngoài ra các phương pháp khác đó là sử dụng cinder, ceph, glusterfs.... Các dạng volume này em chưa làm nên chưa biết sử dụng như thế nào.
  - network: Phần network thì có rất nhiều giải pháp để triển khai network cho các container trong k8s, như là openvswitch, Flannel, OVN,.... Nên em không đi sâu vào từng giải pháp.
- Viết file config để triển khai ứng dụng trên k8s. (`config_file.md`)
- Demo triển khai với ứng dụng webserver với các tính năng: scale, autoscale, update và rollback.

**Comment by ducnc** [comment]
OK! Anh sẽ Accept trước để review cho tiện. Có vấn đề sẽ update sau
